-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'GIFT_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE 'PK_CHALLENGE';
ALTER TYPE "NotificationType" ADD VALUE 'PK_RESULT';
ALTER TYPE "NotificationType" ADD VALUE 'SEAT_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'WITHDRAWAL_UPDATE';
ALTER TYPE "NotificationType" ADD VALUE 'COIN_PURCHASE';
ALTER TYPE "NotificationType" ADD VALUE 'CREATOR_APPLICATION';
ALTER TYPE "NotificationType" ADD VALUE 'MISSED_CALL';
