ALTER TABLE "Call" ADD COLUMN "pricePerMinute" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "Call" ADD COLUMN "billedMinutes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Call" ADD COLUMN "totalCoins" INTEGER NOT NULL DEFAULT 0;

CREATE TABLE "CallPricingConfig" (
  "id" TEXT NOT NULL,
  "pricePerMinute" INTEGER NOT NULL DEFAULT 100,
  "maxDurationMin" INTEGER NOT NULL DEFAULT 60,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "CallPricingConfig_pkey" PRIMARY KEY ("id")
);
