ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "nearbyEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "nearbyLat" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "nearbyLon" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "nearbyUpdatedAt" TIMESTAMP(3);
ALTER TABLE "CreatorSupporter" ADD COLUMN IF NOT EXISTS "fanClubJoinedAt" TIMESTAMP(3);
CREATE INDEX IF NOT EXISTS "User_nearbyEnabled_idx" ON "User"("nearbyEnabled");
CREATE INDEX IF NOT EXISTS "User_nearbyUpdatedAt_idx" ON "User"("nearbyUpdatedAt");
